name: Proper use of variables - secret (tokens), environment variables

on: push

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      CONTAINER_NAME: nice-app-service
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID }}
